apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PROJECT_NAME}}-configmap
  namespace: {{NAMESPACE}}
data:
  # Adicione as variáveis de ambiente não-sensíveis do serviço abaixo
  ENV: "{{STAGE}}"
  PORT: "3000"
  # APP_VAR: "value"