apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{PROJECT_NAME}}-vpa
  namespace: {{NAMESPACE}}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{PROJECT_NAME}}
  updatePolicy:
    # InPlaceOrRecreate: tenta atualizar in-place; recria o pod se necessário
    updateMode: "InPlaceOrRecreate"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 10m
        memory: 32Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
      mode: Auto